# Generated by Django 5.2.10 on 2026-01-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='retal_period',
            new_name='rental_period',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='retal_price_day',
            new_name='rental_price_day',
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'available'), ('rental', 'rental'), ('solid', 'solid')], max_length=50, null=True),
        ),
    ]
