# Generated by Django 5.2.10 on 2026-01-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0002_rename_retal_period_book_rental_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_rental_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
